//Exercicio 91:

{         Solução em Portugol
Algoritmo Exercício91;
VAR
  FUNCIONAMENTO: CARACTER;
  OPERACAO: CARACTER;
FUNCAO MENU( A: CARACTER) : CARACTER;
INICIO
  EXIBA("BEM VINDO A CALCULADORA DA FATEC-BTU!");
  EXIBA("QUAL OPERAÇÃO VOCÊ DESEJA FAZER?");
  LEIA(A);
  MENU <- A;
FIM;
FUNCAO SOMA( J: CARACTER): REAL
VAR
  A,B: REAL;
INICIO
  EXIBA("DIGITE O PRIMEIRO NUMERO DA SOMA: ");
  LEIA(A);
  EXIBA("DIGITE O SEGUNDO NUMERO DA SOMA: ");
  LEIA(B);
  SOMA <- A+B;
FIM;
FUNCAO SUBTRACAO( J: CARACTER): REAL
VAR
  A,B: REAL;
INICIO
  EXIBA("DIGITE O PRIMEIRO NUMERO DA SUBTRACAO: ");
  LEIA(A);
  EXIBA("DIGITE O SEGUNDO NUMERO DA SUBTRACAO: ");
  LEIA(B);
  SUBTRACAO <- A-B;
FIM;
FUNCAO MULTIPLICACAO( J: CARACTER): REAL
VAR
  A,B: REAL;
INICIO
  EXIBA("DIGITE O PRIMEIRO NUMERO DA MULTIPLICAÇÃO: ");
  LEIA(A);
  EXIBA("DIGITE O SEGUNDO NUMERO DA MULTIPLICAÇÃO: ");
  LEIA(B);
  MULTIPLICACAO <- A*B;
FIM;
FUNCAO DIVISAO( A: CARACTER): REAL
VAR
  A,B: REAL;
INICIO
  EXIBA("DIGITE O PRIMEIRO NUMERO DA DIVISAO: ");
  LEIA(A);
  EXIBA("DIGITE O SEGUNDO NUMERO DA DIVISAO: ");
  LEIA(B);
  ENQUANTO( B = 0) FACA
    EXIBA("DIGITE UM NUMERO DIFERENTE DE 0!!");
    LEIA(B);
  FIMENQUANTO;
DIVISAO <- A/B;
FIM;

INICIO
  FUNCIONAMENTO <- "S";
  OPERACAO <- "S";
  ENQUANTO (FUNCIONAMENTO = "S") FACA
    CASO (MENU(OPERACAO)) DE
      "+": EXIBA(SOMA(OPERACAO));
      "-": EXIBA(SUBTRACAO(OPERACAO);
      "*": EXIBA(MULTIPLICACAO(OPERACAO);
      "/": EXIBA(DIVISAO(OPERACAO);
      SENAO
        EXIBA("VOCÊ NÃO DIGITOU UMA OPERAÇÃO VÁLIDA!!");
  FIMCASO;
    EXIBA("DESEJA CONTINUAR USANDO A CALCULADORA?");
    EXIBA("DIGITE S PARA CONTINUAR E QUALQUER OUTRA TECLA PARA SAIR DA CALCULADORA");
    LEIA(FUNCIONAMENTO);
  FIMENQUANTO;
  EXIBA("Até logo!");
FIM.
}

// Solução em Pascal

Program Exercicio;
uses crt;
VAR
  FUNCIONAMENTO: char;
  OPERACAO: char;
Function MENU( A: char) : char;
Begin
  writeln('BEM VINDO A CALCULADORA DA FATEC-BTU!');
  writeln('QUAL OPERAÇÃO VOCÊ DESEJA FAZER?');
  readln(A);
  MENU := A;
End;
Function SOMA( J: Char): Real;
VAR
  A,B: REAL;
Begin
  writeln('DIGITE O PRIMEIRO NUMERO DA SOMA: ');
  readln(A);
  writeln('DIGITE O SEGUNDO NUMERO DA SOMA: ');
  readln(B);
  SOMA := A+B;
End;
Function SUBTRACAO( J: char): real;
VAR
  A,B: REAL;
Begin
  writeln('DIGITE O PRIMEIRO NUMERO DA SUBTRACAO: ');
  readln(A);
  writeln('DIGITE O SEGUNDO NUMERO DA SUBTRACAO: ');
  writeln(B);
  SUBTRACAO := A-B;
End;
Function MULTIPLICACAO( J: char): real;
VAR
  A,B: REAL;
Begin
  writeln('DIGITE O PRIMEIRO NUMERO DA MULTIPLICAÇÃO: ');
  readln(A);
  writeln('DIGITE O SEGUNDO NUMERO DA MULTIPLICAÇÃO: ');
  readln(B);
  MULTIPLICACAO := A*B;
End;
Function DIVISAO( J: char): real;
VAR
  A,B: REAL;
Begin
  writeln('DIGITE O PRIMEIRO NUMERO DA DIVISAO: ');
  readln(A);
  writeln('DIGITE O SEGUNDO NUMERO DA DIVISAO: ');
  readln(B);
  while( B = 0) do
  Begin
    writeln('DIGITE UM NUMERO DIFERENTE DE 0!!');
    readln(B);
  End;
  DIVISAO := A/B;
End;

Begin
  FUNCIONAMENTO := 'S';
  OPERACAO := 'S';
  while (FUNCIONAMENTO = 'S') do
  Begin
    case (MENU(OPERACAO)) of
      '+': writeln(SOMA(OPERACAO):0:2);
      '-': writeln(SUBTRACAO(OPERACAO):0:2);
      '*': writeln(MULTIPLICACAO(OPERACAO):0:2);
      '/': writeln(DIVISAO(OPERACAO):0:2);
      else
        writeln('VOCÊ NÃO DIGITOU UMA OPERAÇÃO VÁLIDA!!');
    End;
    writeln('DESEJA CONTINUAR USANDO A CALCULADORA?');
    writeln('DIGITE S PARA CONTINUAR E QUALQUER OUTRA TECLA PARA SAIR DA CALCULADORA');
    readln(FUNCIONAMENTO);
  end;
  writeln('Até logo!');
  repeat until keypressed;
end.